In [14]:
import numpy as np
from sklearn.model_selection import GroupKFold

X = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
y = np.array([125, 150, 175, 200, 225, 250])
groups = np.array([0.0, 1.23, 0.0, 3, 1.23, 5])
group_kfold = GroupKFold(n_splits=3)
group_kfold.get_n_splits(X, y, groups)

print(group_kfold)
for i, (train_index, test_index) in enumerate(group_kfold.split(X, y, groups)):
    print(f"Fold {i}:")
    print(train_index, test_index)
    print(f"  Train: index={train_index}, data={X[train_index]}, y={y[train_index]}")
    print(f"  Test:  index={test_index}, data={y[test_index]}")
      

GroupKFold(n_splits=3)
Fold 0:
[0 2 3 5] [1 4]
  Train: index=[0 2 3 5], data=[[ 1  2]
 [ 5  6]
 [ 7  8]
 [11 12]], y=[125 175 200 250]
  Test:  index=[1 4], data=[150 225]
Fold 1:
[1 3 4 5] [0 2]
  Train: index=[1 3 4 5], data=[[ 3  4]
 [ 7  8]
 [ 9 10]
 [11 12]], y=[150 200 225 250]
  Test:  index=[0 2], data=[125 175]
Fold 2:
[0 1 2 4] [3 5]
  Train: index=[0 1 2 4], data=[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 9 10]], y=[125 150 175 225]
  Test:  index=[3 5], data=[200 250]
